config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "members#index"

  resources :members

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, :last_name, :date, :presence => true

  def self.search(search)
    members = Member.where("name ILIKE ? OR last_name ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def show
    @member = Member.find(params[:id])
  end

  def index
    if params[:search]
      @members = Member.search(params[:search])
      if @members.empty?
        @members = Member.all
        flash.alert = "Aucune recherche ne correspond à vos critères"
        render :index
      else
        @members
      end
    else
      @members = Member.all
    end
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
      if @member.save
        flash[:success] = "Member created"
        redirect_to members_path
    else
        flash[:alert] = "Creation failed"
        render "new"
    end
  end

  def edit
    @member = Member.find(params[:id])      
  end

  def update
    @member = Member.find(params[:id])

    update_params = params.require(:member).permit(:name, :last_name, :date, :id)

    if @member.update(update_params)
      flash.notice = "Member successfully edited"
      redirect_to root_path
    else
      flash.alert = "Can not be updated"
      render :edit
      flash.alert = nil
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to root_path
  end

  private

  def member_params
    params.permit(:name, :last_name, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_member_path %>">Add a member</a>
      </li>
    </ul>
    <%= form_tag(members_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search" %>
      <%= button_tag(type: "submit", class: "btn btn-info") do %>

          <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/members/edit.html.erb
<div style="height: 10rem;">
  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <% if @member.errors.any? %>
        <ul>
          <% @member.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= form_for @member do |f| %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class: "form-control" %>
          <br /> <br />
        </div>
        <div class="form-group">
          <label> Last Name </label>
          <%= f.text_field :last_name, class: "form-control" %>
          <br /> <br />
        </div>
        <div class="form-group">
          <label> Date </label>
          <%= f.date_field :date, class: "form-control" %>
          <br /> <br />
        </div>
        <button type="submit" class="btn btn-primary" >Edit Member</button>
      <% end %>
    </div>
  </div>
</div>

app/views/members/index.html.erb
<div class="container col-8 mt-5 mb-5">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Last Name</th>
        <th scope="col">First Name</th>
        <th scope="col">Date</th>
      </tr>
    </thead>

    <tbody>
      <% @members.order(id: :asc).each do |x| %>
        <tr scope="row">
          <td><%= x.last_name %></a></td>
          <td><%= x.name %></td>
          <td><%= x.date %></td>
          <td> <a class="btn btn-primary" href="<%= edit_member_path(x.id) %>" role="button">Edit</a> </td>
          <td> <a class="btn btn-danger" href="<%= member_path(x.id) %>" role="button" data-method="DELETE" data-confirm="Are you sure ?">Delete</a> </td>
        </tr>
      <% end %>
    </tbody>
  <table>
</div>

app/views/members/new.html.erb
<div style="height: 5rem;">
  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
    <% if @member.errors.any? %>
    <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= form_tag url_for(action: 'create'), method: "post" do %>
        <div class="form-group-sm">
          <%= label_tag 'Name' %>
          <%= text_field_tag 'name', "", class: "form-control" %>
          <br /> <br />
        </div>
        <div class="form-group-sm">
          <%= label_tag 'Last Name' %>
          <%= text_field_tag 'last_name', "", class: "form-control" %>
          <br /> <br />
        </div>
        <div class="form-group-sm">
          <%= label_tag 'Date' %>
          <%= date_field_tag 'date', "", class: "form-control" %>
          <br /> <br />
          </div>
          <div class="field form-group-sm text-center">
            <%= submit_tag "Create Member", class: "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
</div>